import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from "@/components/Providers";
import Header from "@/components/Header";
import {ClerkProvider} from "@clerk/nextjs";
import {dark} from "@clerk/themes";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider appearance={{
            baseTheme: dark,
            variables: {
                colorPrimary: "#4b919b",
            },
            /*elements: {
                card: {
                    maxWidth: "100%"
                },
            },*/
        }}>
            <html lang="en">
            <body className={inter.className} style={{overflowX: "hidden"}}>
            <Providers>
                <Header/>
                <main className={"container max-w-7xl"}>
                    {children}
                </main>
            </Providers>
            </body>
            </html>
        </ClerkProvider>
    )
}
